- name: mariadb-deployment-apb playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: deprovision-mariadb-deployment-apb
    playbook_debug: false
  tasks:
  - name: Adding the remote host to the inventory
    add_host:
      name: "{{ target_host }}"
      groups: target_group
    changed_when: false
  - name: Adding ssh private key
    shell: "mkdir -p /opt/apb/.ssh && chmod 700 /opt/apb/.ssh && echo -e \"{{ sshprivkey }}\" > /opt/apb/.ssh/id_rsa && chmod 600 /opt/apb/.ssh/id_rsa"

- name: Remove mariadb packages
  remote_user: "{{ remoteuser }}"
  become: yes
  hosts: target_group
  tasks:
    - name: Remove the package from the host
      package:
        name: mariadb
        state: absent


